export interface SurrealTrend {
  id: string;
  emoji: string;
  title: string;
  objectName: string;
  emotion: string;
  style: string;
  body: string;
  limbs: string;
  hair: string;
  cameraAngle: string;
  lighting: string;
  environment: string;
}

export const surrealTrends: SurrealTrend[] = [
  // Food & Drinks
  { id: '1', emoji: '🥚', title: 'البيضة الباكية', objectName: 'Egg', emotion: 'Crying / يبكي', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '2', emoji: '🥕', title: 'الجزرة الغاضبة', objectName: 'Carrot', emotion: 'Angry / غاضب', style: 'Hyperrealistic / واقعي جداً', body: 'جسم نحيل وطويل', limbs: 'جذور/أغصان', hair: 'عشب/نباتات', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '3', emoji: '☕', title: 'القهوة المصدومة', objectName: 'Coffee Cup', emotion: 'Shocked / مصدوم', style: 'Cinematic / سينمائي', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'دخان', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '4', emoji: '🍔', title: 'البرجر الشرير', objectName: 'Burger', emotion: 'Creepy / مخيف', style: 'Hyperrealistic / واقعي جداً', body: 'جسم كرتوني ممتلئ', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '5', emoji: '🍎', title: 'التفاحة المبتسمة', objectName: 'Apple', emotion: 'Smiling / يبتسم', style: '3D Render / ثلاثي الأبعاد', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '6', emoji: '🍕', title: 'البيتزا الحزينة', objectName: 'Pizza Slice', emotion: 'Sad / حزين', style: 'Claymation / صلصال', body: 'بدون جسم (وجه فقط)', limbs: 'أذرع كرتونية', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '7', emoji: '🥦', title: 'البروكلي الحكيم', objectName: 'Broccoli', emotion: 'Neutral / محايد', style: 'Hyperrealistic / واقعي جداً', body: 'جسم بشري كامل', limbs: 'بدون أطراف', hair: 'عشب/نباتات', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '8', emoji: '🌶️', title: 'الفلفل الغاضب', objectName: 'Chili Pepper', emotion: 'Angry / غاضب', style: '3D Render / ثلاثي الأبعاد', body: 'جسم نحيل وطويل', limbs: 'بدون أطراف', hair: 'نار مشتعلة', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '9', emoji: '🍩', title: 'الدونات المصدوم', objectName: 'Donut', emotion: 'Shocked / مصدوم', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '10', emoji: '🍋', title: 'الليمونة المشمئزة', objectName: 'Lemon', emotion: 'Disgusted / مشمئز', style: 'Cinematic / سينمائي', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  
  // Nature & Cosmic
  { id: '11', emoji: '🌍', title: 'الكوكب الباكي', objectName: 'Planet Earth', emotion: 'Crying / يبكي', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '12', emoji: '☀️', title: 'الشمس المبتسمة', objectName: 'Sun', emotion: 'Smiling / يبتسم', style: '3D Render / ثلاثي الأبعاد', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'نار مشتعلة', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '13', emoji: '🌑', title: 'القمر المخيف', objectName: 'Moon', emotion: 'Creepy / مخيف', style: 'Cinematic / سينمائي', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '14', emoji: '🌵', title: 'الصبارة الغاضبة', objectName: 'Cactus', emotion: 'Angry / غاضب', style: 'Hyperrealistic / واقعي جداً', body: 'جسم نحيل وطويل', limbs: 'أذرع كرتونية', hair: 'عشب/نباتات', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '15', emoji: '🍄', title: 'الفطر المصدوم', objectName: 'Mushroom', emotion: 'Shocked / مصدوم', style: 'Claymation / صلصال', body: 'جسم صغير جداً', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '16', emoji: '💧', title: 'قطرة الماء الحزينة', objectName: 'Water Drop', emotion: 'Sad / حزين', style: '3D Render / ثلاثي الأبعاد', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '17', emoji: '🔥', title: 'النار الشريرة', objectName: 'Fire Flame', emotion: 'Creepy / مخيف', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'مخالب', hair: 'نار مشتعلة', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '18', emoji: '☁️', title: 'السحابة المبتسمة', objectName: 'Cloud', emotion: 'Smiling / يبتسم', style: 'Cinematic / سينمائي', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '19', emoji: '🌪️', title: 'الإعصار الغاضب', objectName: 'Tornado', emotion: 'Angry / غاضب', style: '3D Render / ثلاثي الأبعاد', body: 'جسم نحيل وطويل', limbs: 'أذرع كرتونية', hair: 'دخان', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '20', emoji: '⭐', title: 'النجمة المصدومة', objectName: 'Star', emotion: 'Shocked / مصدوم', style: 'Claymation / صلصال', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },

  // Objects & Random
  { id: '21', emoji: '📱', title: 'الهاتف الحزين', objectName: 'Smartphone', emotion: 'Sad / حزين', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '22', emoji: '⏰', title: 'المنبه الغاضب', objectName: 'Alarm Clock', emotion: 'Angry / غاضب', style: '3D Render / ثلاثي الأبعاد', body: 'جسم كرتوني ممتلئ', limbs: 'أذرع كرتونية', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '23', emoji: '💡', title: 'اللمبة المبتسمة', objectName: 'Light Bulb', emotion: 'Smiling / يبتسم', style: 'Cinematic / سينمائي', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '24', emoji: '🗑️', title: 'سلة المهملات المشمئزة', objectName: 'Trash Can', emotion: 'Disgusted / مشمئز', style: 'Hyperrealistic / واقعي جداً', body: 'جسم كرتوني ممتلئ', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '25', emoji: '🧻', title: 'ورق التواليت المصدوم', objectName: 'Toilet Paper', emotion: 'Shocked / مصدوم', style: 'Claymation / صلصال', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '26', emoji: '🔑', title: 'المفتاح الباكي', objectName: 'Key', emotion: 'Crying / يبكي', style: '3D Render / ثلاثي الأبعاد', body: 'جسم نحيل وطويل', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '27', emoji: '🧸', title: 'الدب المخيف', objectName: 'Teddy Bear', emotion: 'Creepy / مخيف', style: 'Hyperrealistic / واقعي جداً', body: 'جسم بشري كامل', limbs: 'مخالب', hair: 'شعر بشري فوضوي', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '28', emoji: '💣', title: 'القنبلة الغاضبة', objectName: 'Bomb', emotion: 'Angry / غاضب', style: 'Cinematic / سينمائي', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'نار مشتعلة', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '29', emoji: '💊', title: 'الحبة المبتسمة', objectName: 'Pill', emotion: 'Smiling / يبتسم', style: '3D Render / ثلاثي الأبعاد', body: 'جسم صغير جداً', limbs: 'أذرع كرتونية', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '30', emoji: '🧠', title: 'الدماغ الحكيم', objectName: 'Brain', emotion: 'Neutral / محايد', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'جذور/أغصان', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  
  // More Random Trends
  { id: '31', emoji: '🦷', title: 'السن الباكي', objectName: 'Tooth', emotion: 'Crying / يبكي', style: 'Claymation / صلصال', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '32', emoji: '🧼', title: 'الصابونة المشمئزة', objectName: 'Soap Bar', emotion: 'Disgusted / مشمئز', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '33', emoji: '🧊', title: 'مكعب الثلج المصدوم', objectName: 'Ice Cube', emotion: 'Shocked / مصدوم', style: 'Cinematic / سينمائي', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '34', emoji: '🧲', title: 'المغناطيس الغاضب', objectName: 'Magnet', emotion: 'Angry / غاضب', style: '3D Render / ثلاثي الأبعاد', body: 'جسم نحيل وطويل', limbs: 'أذرع كرتونية', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '35', emoji: '🔋', title: 'البطارية المبتسمة', objectName: 'Battery', emotion: 'Smiling / يبتسم', style: 'Hyperrealistic / واقعي جداً', body: 'جسم كرتوني ممتلئ', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '36', emoji: '🩸', title: 'قطرة الدم المخيفة', objectName: 'Blood Drop', emotion: 'Creepy / مخيف', style: 'Cinematic / سينمائي', body: 'بدون جسم (وجه فقط)', limbs: 'مخالب', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '37', emoji: '🦠', title: 'الفيروس الشرير', objectName: 'Virus', emotion: 'Angry / غاضب', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'جذور/أغصان', hair: 'عشب/نباتات', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '38', emoji: '🧽', title: 'الإسفنجة الحزينة', objectName: 'Sponge', emotion: 'Sad / حزين', style: 'Claymation / صلصال', body: 'جسم كرتوني ممتلئ', limbs: 'أذرع كرتونية', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '39', emoji: '🪨', title: 'الصخرة الحكيمة', objectName: 'Rock', emotion: 'Neutral / محايد', style: 'Hyperrealistic / واقعي جداً', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'عشب/نباتات', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
  { id: '40', emoji: '🎈', title: 'البالون المصدوم', objectName: 'Balloon', emotion: 'Shocked / مصدوم', style: '3D Render / ثلاثي الأبعاد', body: 'بدون جسم (وجه فقط)', limbs: 'بدون أطراف', hair: 'أصلع (بدون شعر)', cameraAngle: 'زاوية أمامية مباشرة (Front-facing)', lighting: 'إضاءة استوديو ساطعة', environment: 'خلفية بيضاء نقية (Pure White)' },
];
