export const facialExpressions = [
  "ابتسامة عريضة (Wide Smile)",
  "صدمة مبالغ فيها (Exaggerated Shock)",
  "غضب شديد (Intense Anger)",
  "حزن عميق (Deep Sadness)",
  "غمزة مرحة (Playful Wink)",
  "تفكير عميق (Deep Thought)",
  "خوف ورعب (Fear and Terror)",
  "اشمئزاز (Disgust)",
  "ارتباك (Confusion)",
  "ثقة بالنفس (Confident Smirk)",
  "بكاء هستيري (Hysterical Crying)",
  "ضحك مجنون (Maniacal Laugh)",
  "ملل وتثاؤب (Boredom/Yawning)",
  "تركيز شديد (Intense Focus)",
  "إحباط (Frustration)",
  "فرحة غامرة (Overjoyed)",
  "شك وريبة (Suspicious)",
  "تعب وإرهاق (Exhausted)",
  "استفزاز (Provocative)",
  "وجه محايد (Neutral/Deadpan)"
];

export const eyeExpressions = [
  "عيون جاحظة (Bulging Eyes)",
  "عيون نصف مغلقة (Half-closed Eyes)",
  "حواجب معقودة (Furrowed Brows)",
  "عيون دامعة (Teary Eyes)",
  "نظرة جانبية (Side Glance)",
  "عيون واسعة بريئة (Wide Innocent Eyes)",
  "نظرة حادة (Piercing Stare)",
  "عيون لامعة (Sparkling Eyes)",
  "حواجب مرفوعة (Raised Eyebrows)",
  "تحديق مرعب (Creepy Stare)",
  "عيون متعبة بهالات (Tired with Dark Circles)",
  "نظرة متشككة (Squinting/Suspicious)",
  "عيون مغلقة بقوة (Tightly Shut Eyes)",
  "نظرة جنونية (Crazy/Wild Eyes)",
  "عيون حالمة (Dreamy Eyes)",
  "نظرة فارغة (Blank Stare)",
  "عيون متدحرجة (Rolling Eyes)",
  "نظرة غاضبة (Angry Glare)",
  "عيون متوسعة البؤبؤ (Dilated Pupils)",
  "نظرة استهزاء (Mocking Gaze)"
];

export const headShapes = [
  "رأس بيضاوي (Oval)",
  "رأس دائري (Round)",
  "رأس مربع (Square)",
  "رأس مستطيل (Rectangular)",
  "رأس على شكل قلب (Heart-shaped)",
  "رأس ماسي (Diamond)",
  "رأس مثلث (Triangle)",
  "رأس مثلث مقلوب (Inverted Triangle)",
  "رأس عريض من الأسفل (Pear-shaped)",
  "رأس طويل ونحيف (Oblong)",
  "رأس ضخم مبالغ فيه (Exaggerated Large Head)",
  "رأس صغير جداً (Tiny Head)",
  "فك عريض وقوي (Strong Broad Jaw)",
  "ذقن مدبب (Pointy Chin)",
  "جبهة عريضة (Broad Forehead)",
  "رأس مسطح من الأعلى (Flat Top)",
  "رأس غير متماثل (Asymmetrical)",
  "رأس كرتوني منتفخ (Cartoonish Puffy Head)",
  "رأس بملامح حادة (Sharp Angular Features)",
  "رأس بملامح ناعمة (Soft Rounded Features)"
];

export const bodyShapes = [
  "رياضي مفتول العضلات (Muscular/Athletic)",
  "نحيف جداً (Very Skinny)",
  "ممتلئ/سمين (Chubby/Overweight)",
  "متوسط البنية (Average Build)",
  "طويل ونحيل (Tall and Lanky)",
  "قصير وممتلئ (Short and Stocky)",
  "جسم على شكل كمثرى (Pear-shaped Body)",
  "جسم على شكل تفاحة (Apple-shaped Body)",
  "جسم ساعة رملية (Hourglass)",
  "أكتاف عريضة جداً (Broad Shoulders)",
  "جسم كرتوني (رأس كبير وجسم صغير) (Chibi/Cartoon Proportions)",
  "جسم ضخم ومرعب (Hulking/Intimidating)",
  "جسم هزيل وضعيف (Frail/Weak)",
  "جسم مرن ومطاطي (Flexible/Rubber-like)",
  "جسم غير متناسق (Disproportionate)",
  "جسم آلي/سايبورغ (Cyborg/Robotic Build)",
  "جسم وحشي (Monstrous Build)",
  "جسم رشيق (Agile/Lithen)",
  "جسم صلب كالصخر (Rock-solid)",
  "جسم هلامي (Jelly-like/Soft)"
];

export const eyeColors = [
  "بني غامق (Dark Brown)",
  "بني فاتح (Light Brown)",
  "أزرق سماوي (Sky Blue)",
  "أزرق داكن (Deep Blue)",
  "أخضر زمردي (Emerald Green)",
  "أخضر فاتح (Light Green)",
  "عسلي (Hazel)",
  "رمادي (Gray)",
  "أسود فاحم (Pitch Black)",
  "أحمر متوهج (Glowing Red)",
  "أرجواني/بنفسجي (Purple/Violet)",
  "أصفر/ذهبي (Yellow/Golden)",
  "أبيض بالكامل (بدون بؤبؤ) (All White/Blind)",
  "وردي (Pink)",
  "برتقالي ناري (Fiery Orange)",
  "عيون متغايرة (لونين مختلفين) (Heterochromia)",
  "عيون قطة (Cat Eyes)",
  "عيون بألوان قوس قزح (Rainbow Eyes)",
  "عيون فضية لامعة (Shiny Silver)",
  "عيون نيون مضيئة (Neon Glowing Eyes)"
];

export const emotions = [
  "حماس مفرط (Extreme Excitement)",
  "رعب شديد (Pure Terror)",
  "يأس وإحباط (Despair)",
  "غضب عارم (Rage)",
  "سعادة غامرة (Pure Joy)",
  "صدمة واكتشاف (Shocked Discovery)",
  "حيرة وارتباك (Bewilderment)",
  "ثقة وغرور (Arrogance/Confidence)",
  "حزن وبكاء (Sorrow)",
  "اشمئزاز وقرف (Disgust)",
  "ملل لامبالي (Apathy)",
  "ترقب وتوتر (Suspense/Anxiety)",
  "حب وإعجاب (Adoration/Love)",
  "غيرة وحسد (Jealousy)",
  "إحراج وخجل (Embarrassment)",
  "فخر واعتزاز (Pride)",
  "شعور بالذنب (Guilt)",
  "راحة واسترخاء (Relief)",
  "طمع وجشع (Greed)",
  "جنون وهوس (Madness/Mania)"
];

export const bodyPoses = [
  "إشارة باليد نحو الكاميرا (Pointing at Camera)",
  "إمساك الرأس باليدين من الصدمة (Hands on Head in Shock)",
  "تكتيف الذراعين بثقة (Crossed Arms)",
  "القفز في الهواء (Jumping in Air)",
  "الركض نحو الكاميرا (Running towards Camera)",
  "الهروب والنظر للخلف (Running away looking back)",
  "الوقوف بوضعية قتالية (Fighting Stance)",
  "الجلوس على الأرض بيأس (Sitting on floor in despair)",
  "الاستناد على جدار (Leaning on wall)",
  "رفع اليدين احتفالاً (Raising hands in victory)",
  "تغطية الوجه باليدين (Covering face with hands)",
  "إمساك شيء وعرضه للكاميرا (Holding object to camera)",
  "وضعية التفكير (يد على الذقن) (Thinking pose)",
  "السقوط أو التعثر (Falling/Tripping)",
  "الزحف على الأرض (Crawling)",
  "النظر من خلف زاوية (Peeking from corner)",
  "وضعية البطل الخارق (Superhero landing/pose)",
  "الركوع على ركبة واحدة (Kneeling)",
  "التلويح باليد (Waving)",
  "وضعية استرخاء على كرسي (Lounging on chair)"
];

export const channelNiches = [
  "ألعاب (Gaming)",
  "تقنية ومراجعات (Tech & Reviews)",
  "فلوجات وحياة يومية (Vlogs & Lifestyle)",
  "تحديات ومقالب (Challenges & Pranks)",
  "تعليم وتطوير ذات (Education & Self-Development)",
  "طبخ ووصفات (Cooking & Food)",
  "رياضة ولياقة (Sports & Fitness)",
  "اقتصاد وأعمال (Finance & Business)",
  "وثائقيات وقصص (Documentaries & Stories)",
  "رعب وغموض (Horror & Mystery)",
  "كوميديا وسكيتشات (Comedy & Sketches)",
  "سفر ومغامرات (Travel & Adventure)",
  "مكياج وتجميل (Beauty & Makeup)",
  "موسيقى وعزف (Music & Covers)",
  "بودكاست ومقابلات (Podcasts & Interviews)",
  "أخبار وتحليلات (News & Commentary)",
  "تاريخ وثقافة (History & Culture)",
  "علوم وفضاء (Science & Space)",
  "حيوانات أليفة (Pets & Animals)",
  "سيارات ومحركات (Cars & Automotive)",
  "تصميم وفن (Art & Design)",
  "برمجة وتطوير (Programming & Coding)",
  "صحة وطب (Health & Medicine)",
  "عقارات (Real Estate)",
  "مراجعة أفلام ومسلسلات (Movies & TV Reviews)",
  "أنمي ومانجا (Anime & Manga)",
  "ردود أفعال (Reacts)",
  "ASMR",
  "تجارب علمية (Science Experiments)",
  "أعمال يدوية (DIY & Crafts)"
];

export const videoTypes = [
  "كيف تفعل... (How-to / Tutorial)",
  "أفضل 10... (Top 10 List)",
  "مراجعة شاملة (Full Review)",
  "تحدي 24 ساعة (24 Hour Challenge)",
  "قصة حياتي (My Story / Draw My Life)",
  "ردة فعلي على... (Reaction Video)",
  "مقارنة بين... (Comparison)",
  "فتح صندوق (Unboxing)",
  "جولة في غرفتي/مكتبي (Room/Desk Tour)",
  "ماذا يوجد في حقيبتي (What's in my bag)",
  "روتيني الصباحي/المسائي (Morning/Night Routine)",
  "أسئلة وأجوبة (Q&A)",
  "بث مباشر (Live Stream Highlights)",
  "كواليس (Behind the Scenes)",
  "أخطاء شائعة (Common Mistakes)",
  "نصائح وحيل (Tips & Tricks)",
  "تحديثات وأخبار (Updates & News)",
  "تجربة منتج غريب (Testing Weird Products)",
  "تحدي الأكل (Food Challenge / Mukbang)",
  "مقلب في صديقي (Prank on Friend)",
  "وثائقي قصير (Short Documentary)",
  "تحليل شخصية/فيلم (Character/Movie Analysis)",
  "توقعات للمستقبل (Future Predictions)",
  "شرح مبسط (Explained Simply)",
  "مقابلة مع... (Interview with...)",
  "تجربتي مع... (My Experience with...)",
  "تحدي بدون ميزانية (Zero Budget Challenge)",
  "صرفت مليون دولار على... (Spent $1M on...)",
  "اشتريت أغلى/أرخص... (Bought the most expensive/cheapest...)",
  "تحدي البقاء (Survival Challenge)",
  "تعلمت مهارة في 30 يوم (Learned a skill in 30 days)",
  "يوم كامل في حياة... (A day in the life of...)",
  "فلوج سفر (Travel Vlog)",
  "تحدي اللياقة البدنية (Fitness Challenge)",
  "تغيير جذري (Extreme Makeover)",
  "تحدي الموضة (Fashion Challenge)",
  "مشترياتي (Haul)",
  "تحدي الرسم (Drawing Challenge)",
  "قصة رعب حقيقية (True Horror Story)",
  "لغز لم يحل (Unsolved Mystery)",
  "نظريات المؤامرة (Conspiracy Theories)",
  "تحدي الضحك (Try Not to Laugh)",
  "تجميع مقاطع مضحكة (Funny Compilation)",
  "تحدي الألعاب (Gaming Challenge)",
  "تختيم لعبة (Let's Play / Walkthrough)",
  "أسرار في اللعبة (Easter Eggs & Secrets)",
  "تحدي السرعة (Speedrun)",
  "تحدي البناء (Building Challenge)",
  "تحدي البرمجة (Coding Challenge)",
  "تصميم موقع في ساعة (Design a website in 1 hour)",
  "تحدي التصوير (Photography Challenge)",
  "تعديل صور المتابعين (Editing Subscribers' Photos)",
  "تحدي الطبخ (Cooking Challenge)",
  "وصفة سرية (Secret Recipe)",
  "تذوق طعام الشارع (Street Food Tasting)",
  "تحدي المكياج (Makeup Challenge)",
  "روتين العناية بالبشرة (Skincare Routine)",
  "تحدي الأناقة (Style Challenge)",
  "تحدي الموسيقى (Music Challenge)",
  "تأليف أغنية في ساعة (Writing a song in 1 hour)",
  "عزف غطاء (Cover Song)",
  "تحدي الرياضة (Sports Challenge)",
  "تحليل مباراة (Match Analysis)",
  "تحدي المهارات (Skills Challenge)",
  "تحدي السيارات (Car Challenge)",
  "تعديل سيارة (Car Modification)",
  "تحدي السرعة (Drag Race)",
  "تحدي الحيوانات (Pet Challenge)",
  "تدريب كلب (Dog Training)",
  "تحدي العلوم (Science Challenge)",
  "تجربة كيميائية (Chemistry Experiment)",
  "تحدي الفضاء (Space Challenge)",
  "تحدي التاريخ (History Challenge)",
  "قصة تاريخية (Historical Story)",
  "تحدي الجغرافيا (Geography Challenge)",
  "تحدي اللغات (Language Challenge)",
  "تعلم لغة في أسبوع (Learn a language in a week)",
  "تحدي القراءة (Reading Challenge)",
  "مراجعة كتاب (Book Review)",
  "تحدي الكتابة (Writing Challenge)",
  "تحدي الأعمال (Business Challenge)",
  "كيف تبدأ مشروعك (How to start a business)",
  "تحدي الاستثمار (Investment Challenge)",
  "تحدي العقارات (Real Estate Challenge)",
  "تحدي العملات الرقمية (Crypto Challenge)",
  "تحدي التداول (Trading Challenge)",
  "تحدي التسويق (Marketing Challenge)",
  "تحدي المبيعات (Sales Challenge)",
  "تحدي الإنتاجية (Productivity Challenge)",
  "كيف تنظم وقتك (How to organize your time)",
  "تحدي العادات (Habits Challenge)",
  "تحدي التأمل (Meditation Challenge)",
  "تحدي النوم (Sleep Challenge)",
  "تحدي الصحة النفسية (Mental Health Challenge)",
  "تحدي السعادة (Happiness Challenge)",
  "تحدي العلاقات (Relationships Challenge)",
  "تحدي التواصل (Communication Challenge)",
  "تحدي القيادة (Leadership Challenge)",
  "تحدي الإبداع (Creativity Challenge)",
  "تحدي الابتكار (Innovation Challenge)"
];

export const brandColors = [
  "أحمر، أسود، أبيض (Red, Black, White - Aggressive/Action)",
  "أزرق، أبيض، رمادي (Blue, White, Gray - Trust/Tech)",
  "أصفر، أسود، أبيض (Yellow, Black, White - Warning/Attention)",
  "أخضر، أسود، ذهبي (Green, Black, Gold - Wealth/Finance)",
  "بنفسجي، وردي، أزرق فاتح (Purple, Pink, Light Blue - Gaming/Neon)",
  "برتقالي، أزرق داكن، أبيض (Orange, Navy, White - Energetic/Sports)",
  "وردي، أبيض، ذهبي وردي (Pink, White, Rose Gold - Beauty/Lifestyle)",
  "أخضر فاتح، بني، بيج (Light Green, Brown, Beige - Nature/Organic)",
  "أسود، ذهبي، فضي (Black, Gold, Silver - Luxury/Premium)",
  "أزرق سماوي، أصفر، أبيض (Sky Blue, Yellow, White - Cheerful/Vlog)",
  "أحمر داكن، أسود، رمادي غامق (Dark Red, Black, Dark Gray - Horror/Mystery)",
  "أخضر نيون، أسود، أرجواني (Neon Green, Black, Purple - Cyberpunk/Hacker)",
  "أزرق مخضر، مرجاني، كريمي (Teal, Coral, Cream - Travel/Summer)",
  "أرجواني داكن، ذهبي، أسود (Dark Purple, Gold, Black - Royal/Mystic)",
  "أبيض، رمادي فاتح، أسود (White, Light Gray, Black - Minimalist/Apple style)",
  "أصفر نيون، وردي نيون، أزرق نيون (Neon Yellow, Neon Pink, Neon Blue - Pop/GenZ)",
  "بني داكن، برتقالي محروق، بيج (Dark Brown, Burnt Orange, Beige - Cozy/Autumn)",
  "أزرق فاتح جداً، أبيض، فضي (Ice Blue, White, Silver - Clean/Medical)",
  "أحمر ساطع، أصفر ساطع، أزرق ساطع (Bright Red, Bright Yellow, Bright Blue - Kids/Toys)",
  "أسود فاحم، أبيض ناصع، أحمر دموي (Pitch Black, Pure White, Blood Red - True Crime)"
];

export const styles = [
  // أساليب قنوات أجنبية
  "MrBeast (ألوان فاقعة، تباين عالي، تعابير مبالغ فيها، أسهم حمراء)",
  "Ali Abdaal (إضاءة ناعمة، جمالي، نظيف، إنتاجية، ألوان باستيل)",
  "MagnatesMedia (وثائقي، سينمائي مظلم، غموض، أعمال، نسيج ورقي)",
  "PewDiePie (ألعاب، فوضوي، حماسي، إضاءة RGB، ميمز)",
  "Kurzgesagt (رسم فيكتور، ألوان مسطحة، علمي، فضاء، طيور)",
  "Iman Gadzhi (تطوير الذات، ألوان دافئة، فخامة، بدلات، ساعات)",
  "MKBHD (تقنية، نظيف جداً، إضاءة حمراء/سوداء، زوايا حادة)",
  "Linus Tech Tips (تقنية، تعابير مضحكة، منتجات في اليد، خلفية ورشة)",
  "Dude Perfect (رياضة، حماس، ألوان زاهية، نيون، حركة سريعة)",
  "Logan Paul (فلوج، صدمة، ألوان مشبعة، نصوص ضخمة)",
  "Emma Chamberlain (فلوج، عفوي، كاميرا قديمة، فلاتر دافئة)",
  "Markiplier (ألعاب رعب، ظلام، إضاءة حمراء على الوجه، رعب)",
  "Jacksepticeye (ألعاب، إضاءة خضراء، طاقة عالية، صراخ)",
  "Dream (ماينكرافت، ألوان خضراء، رسم بسيط، حركة)",
  "TommyInnit (ألعاب، فوضى، نصوص حمراء وبيضاء، تعابير مصدومة)",
  "Sidemen (تحديات، مجموعة أشخاص، ألوان زاهية، نصوص كبيرة)",
  "Beta Squad (تحديات، شوارع لندن، ألوان مشبعة، تعابير مضحكة)",
  "Veritasium (علوم، واقعي، إضاءة طبيعية، نصوص واضحة)",
  "Vsauce (علوم، نظرة غامضة، خلفية بيضاء/سوداء، أسئلة)",
  "SmarterEveryDay (علوم، تجارب، حركة بطيئة، طبيعة)",
  "Mark Rober (هندسة، تجارب مجنونة، ألوان زاهية، اختراعات)",
  "Colin Furze (اختراعات، فوضى، شرارات، ورشة عمل)",
  "Peter McKinnon (تصوير، سينمائي، قهوة، ألوان بنية/سوداء)",
  "Casey Neistat (فلوج، نيويورك، نظارات شمسية، حركة سريعة)",
  "Yes Theory (مغامرة، إيجابية، ألوان دافئة، سفر)",
  "Kara and Nate (سفر، ابتسامات، مناظر طبيعية، ألوان زاهية)",
  "Gordon Ramsay (طبخ، غضب، نار، طعام شهي، إضاءة درامية)",
  "Babish Culinary Universe (طبخ، نظيف، إضاءة علوية، طعام)",
  "Joshua Weissman (طبخ، سينمائي، سريع، طعام، إضاءة دافئة)",
  "Marques Brownlee (تقنية، أسود وأحمر، نظيف، منتجات)",
  "iJustine (تقنية، وردي، ألوان زاهية، ابتسامة)",
  "Mrwhosetheboss (تقنية، إضاءة استوديو، ألوان زرقاء/بنفسجية)",
  "JerryRigEverything (تقنية، تدمير، أدوات، خلفية بيضاء)",
  "Graham Stephan (مالية، استوديو، ألوان زرقاء، نصوص مالية)",
  "Andrei Jikh (مالية، سحر، عملات رقمية، إضاءة نيون)",
  "Meet Kevin (مالية، أخبار، نصوص كبيرة، تعابير جادة)",
  "Coffeezilla (تحقيق، استوديو مظلم، شاشات، غموض)",
  "Nexpo (رعب، إنترنت مظلم، أسود وأبيض، تشويش)",
  "Lemmino (وثائقي، رسم متحرك، ألوان هادئة، غموض)",
  "Oversimplified (تاريخ، رسم كرتوني بسيط، ألوان مسطحة)",
  "Bill Wurtz (تاريخ، نيون، نصوص متحركة، فوضى بصرية)",
  "TierZoo (ألعاب/حيوانات، رسومات ألعاب، ألوان زاهية)",
  "Daily Dose of Internet (منوعات، بسيط، صورة من الفيديو)",
  "FailArmy (كوميديا، فشل، نصوص حمراء، أسهم)",
  "First We Feast (مقابلات، أجنحة حارة، خلفية سوداء)",
  "WIRED (مقابلات، خلفية بيضاء، نصوص حمراء، نظيف)",
  "Vogue (موضة، سينمائي، إضاءة ناعمة، جمالي)",
  "Architectural Digest (عقارات، إضاءة طبيعية، فخامة)",
  "Lofi Girl (موسيقى، رسم أنمي، استرخاء، ألوان دافئة)",
  
  // أساليب قنوات عربية
  "أبو فلة (AboFlah - ألعاب، خيري، حماس مفرط، ألوان زاهية، ابتسامة عريضة)",
  "بندريتا (BanderitaX - ألعاب، ضحك، تعابير مضحكة، إضاءة استوديو)",
  "الدحيح (Daheeh - علوم، كوميديا، خلفية سوداء، إضاءة مركزة، تعابير مسرحية)",
  "جو حطاب (Joe Hattab - سفر، سينمائي، ألوان دافئة، مناظر طبيعية، وجوه محلية)",
  "ابن سوريا (Ibn Syria - ببجي، حماس، ألوان مشبعة، نصوص ضخمة)",
  "أحمد أبو الرُّب (Ahmad Aburob - نقد، كوميديا، تعابير ساخرة، خلفية ملونة)",
  "عمر يجرب (Omar Tries - تجارب، ألوان زاهية، منتجات غريبة، صدمة)",
  "سحس (S7S - تحديات أكل، كميات ضخمة، ألوان دافئة، طعام شهي)",
  "أسامة زيرو (Osama Zero - برمجة، نظيف، ألوان زرقاء، شاشات كود)",
  "دروس أونلاين (Droos Online - تعليم، إضاءة ناعمة، ألوان هادئة، إنتاجية)",
  "علي محمد علي (Ali Muhammad Ali - كتب، تلخيص، مكتبة، إضاءة دافئة)",
  "مخبر الاقتصاد (Mokhber El Iktissad - اقتصاد، رسوم بيانية، ألوان جادة، غموض)",
  "مساحة (Misa7a - وثائقي، تاريخ، إضاءة درامية، صور قديمة)",
  "متع عقلك (Mata3 3a2lak - معلومات، ألوان غامضة، صور غريبة، نصوص مثيرة)",
  "هل تعلم؟ (Hal Ta3lam - حقائق، ألوان زاهية، صور جذابة)",
  "عشوائيات (3ashwa2yat - معلومات، تصميم نظيف، ألوان متباينة)",
  "الاسبتالية (Elesptalia - طب، إضاءة بيضاء، نظيف، ألوان زرقاء/خضراء)",
  "إياد موج (Eyad Mooj - تقنية، إضاءة نيون، ألوان داكنة، منتجات)",
  "فيصل السيف (Faisal Alsaif - تقنية، استوديو احترافي، ألوان زرقاء)",
  "رقمي تي في (Raqami TV - تقنية، أخبار، تصميم إخباري، نصوص واضحة)",
  "محمد عدنان (Mohamed Adnan - رياضة، حماس، ألوان الملاعب، لاعبين)",
  "ممدوح نصر الله (Mamdouh Nasrallah - رياضة، تحليل، استوديو، تعابير جادة)",
  "صباحو كورة (Sabaho Kora - رياضة، كوميديا، ألوان زاهية)",
  "نور ستارز (Noor Stars - فلوج، مكياج، ألوان وردية، إضاءة ناعمة)",
  "نارين بيوتي (Narins Beauty - فلوج، ألوان باستيل، جمالي)",
  "غيث مروان (Ghaith Marwan - فلوج، تحديات، ألوان زاهية، أصدقاء)",
  "أنس وأصالة (Anasala Family - عائلة، ألوان دافئة، سعادة)",
  "عائلة مشيع (Mmoshaya - عائلة، أطفال، ألوان زاهية، مقالب)",
  "شبكة ألعاب العرب (Arab Games Network - ألعاب، ماينكرافت، ألوان مشبعة)",
  "سيد (Sayed - ألعاب، رعب، إضاءة حمراء، صدمة)",
  "أبو سروال (Abo Serwal - ألعاب، كوميديا، ميمز، ألوان فاقعة)",
  "مجرم قيمز (MjrmGames - ألعاب، تحديات، ألوان داكنة)",
  "فراس قيمر (Firas Gamer - ألعاب، بناء، ألوان زاهية)",
  "مصطفى جيم أوفر (Mustafa Game Over - ألعاب، حماس، نصوص كبيرة)",
  "علي المرجاني (Ali Almerjany - ألعاب، تعابير مضحكة، إضاءة استوديو)",
  "حسن هاشم (Hasan Hashim - غموض، إضاءة خافتة، ألوان داكنة، تشويق)",
  "قصة حقيقية (True Story - رسوم متحركة، ألوان زاهية، دراما)",
  "حبر يطوى (Hebr Yotwa - قصص، إضاءة درامية، ألوان بنية)",
  "سيارات (Cars - سرعة، ألوان معدنية، إضاءة خارجية)",
  "عرب جي تي (ArabGT - سيارات، احترافي، ألوان داكنة، دخان)",
  
  // أساليب فنية عامة
  "وثائقي جريمة (أبيض وأسود مع أحمر، غامض، مخيف، نسيج خشن)",
  "سايبربانك (Cyberpunk - نيون، أرجواني/أزرق، مدينة مستقبلية، تباين عالي)",
  "ريترو 80s (Retro 80s - ألوان نيون، شبكات، غروب شمس، VHS)",
  "فيكتوري / ستيم بانك (Steampunk - نحاس، تروس، بخار، ألوان بنية)",
  "أنمي ياباني (Japanese Anime - ألوان مشبعة، خطوط حادة، عيون كبيرة)",
  "كوميكس / قصص مصورة (Comic Book - نقاط نصفية، خطوط سوداء عريضة، ألوان أساسية)",
  "ألوان مائية (Watercolor - ألوان ناعمة، حواف متداخلة، إضاءة طبيعية)",
  "تصميم مسطح (Flat Design - ألوان صلبة، بدون ظلال، نظيف جداً)",
  "ثلاثي الأبعاد واقعي (3D Realistic - إضاءة سينمائية، خامات دقيقة، انعكاسات)",
  "فن البوب (Pop Art - ألوان فاقعة جداً، تباين عالي، نقاط)",
  "تصوير فوتوغرافي ماكرو (Macro Photography - تركيز شديد، خلفية ضبابية جداً)"
];

export const aspectRatios = [
  "16:9 (يوتيوب قياسي - Landscape)",
  "9:16 (يوتيوب شورتس / تيك توك - Portrait)",
  "1:1 (انستجرام / مربع - Square)",
  "4:3 (شاشات قديمة / كلاسيكي)"
];
